/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;

import cwms.DataLayer.Common.ConnectionType;
import cwms.DataLayer.Common.DataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import cwms.controller.CustomerHandler;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Asanka
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    
    public AddCustomer() {
        initComponents();
        
        DataBase db = new DataBase(ConnectionType.MYSQL);
        con = db.getConnection();
        
       
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cus_nic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cus_mobile = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cus_land = new javax.swing.JTextField();
        gprofile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cus_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cus_add = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel2.setBackground(new java.awt.Color(25, 77, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 142, -1, -1));
        jPanel2.add(cus_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 144, 349, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer NIC :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 182, -1, -1));
        jPanel2.add(cus_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 184, 349, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer address : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 356, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Mobile :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 222, 136, -1));
        jPanel2.add(cus_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 224, 349, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Suffix :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 313, 136, -1));

        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Mr");
        jPanel2.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 313, -1, -1));

        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Mrs");
        jPanel2.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 313, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer land phone Number :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 262, -1, -1));
        jPanel2.add(cus_land, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 264, 349, -1));

        gprofile.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        gprofile.setText("Generate customer profiile");
        gprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gprofileActionPerformed(evt);
            }
        });
        jPanel2.add(gprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 620, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customer Email :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 467, 136, -1));
        jPanel2.add(cus_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 469, 349, -1));

        cus_add.setColumns(20);
        cus_add.setRows(5);
        jScrollPane1.setViewportView(cus_add);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 356, 349, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Customer");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 28, -1, -1));

        jButton8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 624, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 19, 45, 42));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 19, 45, 42));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Main m1=new Main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          CusMain m2=new CusMain();
        m2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void gprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gprofileActionPerformed
        // TODO add your handling code here:
        String name = cus_name.getText();
        String nic = cus_nic.getText();
        String mobile = cus_mobile.getText();
        String land = cus_land.getText();
        String address = cus_add.getText();
        String email = cus_email.getText();
        CustomerHandler ch = new CustomerHandler();
        
        //mobile number validation
           Pattern pnumPattern = Pattern.compile("(\\d{10})*");
           Matcher mat = pnumPattern.matcher(mobile);
            if (!mat.matches()) {
                JOptionPane.showMessageDialog(null, "Invalid Mobile No");
           
            
             //land number validation
                Pattern lnumPattern = Pattern.compile("(\\d{10})*");
                Matcher matc = lnumPattern.matcher(land);
                if (!matc.matches()) {
                    JOptionPane.showMessageDialog(null, "Invalid Land Phone No");
                    return;  
                }
                
                //nic validation
                Pattern nicPattern = Pattern.compile("(\\d{9}[V])*");
                mat = nicPattern.matcher(nic);
                if (!mat.matches()) {
                    JOptionPane.showMessageDialog(null, "Invalid NIC");
                    return;
                }
                
                //email validation
                Pattern emailPattern = Pattern.compile("(^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$)", Pattern.CASE_INSENSITIVE);
                Matcher mtch = emailPattern.matcher(email);
                if (!mtch.matches()) {
                        JOptionPane.showMessageDialog(null, "Invalid Email");
                        return;
                
                }
            }
            else {
                Pattern lnumPattern = Pattern.compile("(\\d{10})*");
                Matcher mt = lnumPattern.matcher(land);
                 if (!mt.matches()) {
                    JOptionPane.showMessageDialog(null, "Invalid Land Phone No");
                    return;  
                  }
                 Pattern nicPattern = Pattern.compile("(\\d{9}[V])*");
                 mat = nicPattern.matcher(nic);
                if (!mat.matches()) {
                    JOptionPane.showMessageDialog(null, "Invalid NIC");
                    return;
                }
                
                //email validation
                Pattern emailPattern = Pattern.compile("(^[A-Za-z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$)", Pattern.CASE_INSENSITIVE);
                Matcher mtch = emailPattern.matcher(email);
                if (!mtch.matches()) {
                        JOptionPane.showMessageDialog(null, "Invalid Email");
                        return;
                
                }
            }
        String suffix;
        if(m.isSelected())
        {
            suffix = m.getText();
            ch.addCustomer(name,email,address, mobile , suffix, nic,land);
        }
        if(f.isSelected())
        {
            suffix = f.getText();
            ch.addCustomer(name,email,address, mobile , suffix, nic,land);
        }
           
        
        JOptionPane.showMessageDialog(null, "Sucessfully added.....");
        
        
        
        cus_name.setText("");
        cus_nic.setText("");
        cus_mobile.setText("");
        cus_land.setText("");
        cus_add.setText("");
        cus_email.setText("");
        
        //this.dispose();
        //new CustomerSumary(name, address,mobile,land,email, nic);
    }//GEN-LAST:event_gprofileActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea cus_add;
    private javax.swing.JTextField cus_email;
    private javax.swing.JTextField cus_land;
    private javax.swing.JTextField cus_mobile;
    private javax.swing.JTextField cus_name;
    private javax.swing.JTextField cus_nic;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton gprofile;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton m;
    // End of variables declaration//GEN-END:variables
}
