/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;
import cwms.DataLayer.Common.ConnectionType;
import cwms.DataLayer.Common.DataBase;
import cwms.DataLayer.DataAccess;
import cwms.controller.EmployeeHandler;
import cwms.model.Employee;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Asanka
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        
        initComponents();
        positionCmb.setSelectedItem(null);
        
    }
    private String checkNic(String nic)
    {
        String dbnic=""; 
        try {
            DataBase d=new DataBase(ConnectionType.MYSQL);
            Connection conn=d.getConnection();
            ResultSet resultset = null;
            String sql = "SELECT DISTINCT emp_nic FROM past_employee_info WHERE emp_nic=?  ";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1,nic);

            resultset = statement.executeQuery();
           
            while (resultset.next()) {
                dbnic = (resultset.getString(1));
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return dbnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        GenProfileBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nicTxt = new javax.swing.JTextField();
        mRadBtn = new javax.swing.JRadioButton();
        fRadBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        positionCmb = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        addTxt = new javax.swing.JTextArea();
        addfingerprintBtn = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jScrollPane1.setViewportView(jEditorPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 77, 25));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Employee");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name :");

        fnameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameTxtFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender      :");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address     :");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone :");

        phoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneTxtFocusLost(evt);
            }
        });

        GenProfileBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        GenProfileBtn.setText("Generate Profile");
        GenProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenProfileBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Exit_26px.png")); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC :");

        nicTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicTxtFocusLost(evt);
            }
        });

        mRadBtn.setBackground(new java.awt.Color(25, 77, 25));
        mRadBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        mRadBtn.setForeground(new java.awt.Color(255, 255, 255));
        mRadBtn.setText("Male");

        fRadBtn.setBackground(new java.awt.Color(25, 77, 25));
        fRadBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        fRadBtn.setForeground(new java.awt.Color(255, 255, 255));
        fRadBtn.setText("Female");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Position:");

        positionCmb.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        positionCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Director", "Manager", "Permanent", "Casual" }));

        addTxt.setColumns(20);
        addTxt.setRows(5);
        addTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addTxtFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(addTxt);

        addfingerprintBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        addfingerprintBtn.setText("Add Fingerprint");
        addfingerprintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfingerprintBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(GenProfileBtn)
                .addGap(42, 42, 42)
                .addComponent(addfingerprintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetBtn)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mRadBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fRadBtn))
                                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(343, 343, 343))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mRadBtn)
                    .addComponent(fRadBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(positionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(GenProfileBtn)
                    .addComponent(addfingerprintBtn))
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
      Main m1=new Main();
      m1.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        String cmessage = "Do you wish to add more employees?";   
        String conf = "Exit";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf, JOptionPane.YES_NO_OPTION);
         if(confirm == JOptionPane.YES_NO_OPTION){
               JOptionPane.getRootFrame().dispose();
                fnameTxt.setText(null);
                addTxt.setText(null);
                phoneTxt.setText(null);
                nicTxt.setText(null);
                fRadBtn.setSelected(false);
                mRadBtn.setSelected(false);
                positionCmb.setSelectedItem(null);
              
        }
         else
        {
                 EmployeeMain m2=new  EmployeeMain();
                 m2.setVisible(true);
                 this.dispose();
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void GenProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenProfileBtnActionPerformed
        boolean check;
        String emname=fnameTxt.getText().trim();
       
        String emgen;
        if(fRadBtn.isSelected())
            emgen="F";
        else
            emgen="M";
        
       
        String emadd=addTxt.getText().trim();
        String emcont=phoneTxt.getText().trim();
        String empnic=nicTxt.getText().trim();
        String emppos=positionCmb.getSelectedItem().toString();

           String dnic=checkNic(empnic);
            if(dnic.equals(empnic))
            {
                int response = JOptionPane.showConfirmDialog(null, "NIC already exists.Do you want to continue adding this employee?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                    if (response == JOptionPane.YES_OPTION) 
                    {
                        DataAccess da=new DataAccess();
                        //boolean r=da.addExistingEmployee(empnic);
                        //if(r)
                        {
                            JOptionPane.showMessageDialog(null,"Successfully added");
                        }
                        
                    }               
                    else
                    {
                        EmployeeMain em=new EmployeeMain();
                        this.dispose();
                        em.setVisible(true);
                    }
            }
            else
            {
                EmployeeHandler eh=new EmployeeHandler();
                check=eh.addEmployee(emname,empnic,emadd, emcont, emgen,emppos);
        
                if(check)
                {
                    JOptionPane.showMessageDialog(this,"Employee details has been successfully added to the system");
                    this.dispose();
                    EmployeeMain em=new EmployeeMain();
                    em.setVisible(true);
                }
            }
    }//GEN-LAST:event_GenProfileBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
       fnameTxt.setText(null);
       addTxt.setText(null);
       phoneTxt.setText(null);
       nicTxt.setText(null);
       positionCmb.setSelectedItem(null);
       fRadBtn.setSelected(false);
       mRadBtn.setSelected(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void fnameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameTxtFocusLost
       String fn=fnameTxt.getText().trim();
       if(fn.isEmpty()) 
       {
           fnameTxt.setForeground(Color.RED);
           fnameTxt.setText("This field must be populated");
        }
    }//GEN-LAST:event_fnameTxtFocusLost

    private void phoneTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTxtFocusLost
        String pn=phoneTxt.getText().trim();
        
       if(pn.isEmpty()) 
       {
           phoneTxt.setForeground(Color.RED);
           phoneTxt.setText("This field must be populated!!!");
        
       }
       else if(pn.length()>10)
       {
           phoneTxt.setForeground(Color.RED);
           phoneTxt.setText("Phone number too long!!!");
           
       }
       else if(pn.length()<10)
       {
           phoneTxt.setForeground(Color.RED);
           phoneTxt.setText("Phone number too short!!!");
       }
      else
       {
           Pattern pnumPattern = Pattern.compile("(\\d{10})*");
           Matcher m = pnumPattern.matcher(pn);
            if (!m.matches())
            {
                phoneTxt.setForeground(Color.RED);
                phoneTxt.setText("Invalid phone number!!!");  
            }
            else
            {
                
            }
       }
    }//GEN-LAST:event_phoneTxtFocusLost

    private void phoneTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTxtFocusGained
       phoneTxt.setForeground(Color.BLACK);
       phoneTxt.setText(null);
    }//GEN-LAST:event_phoneTxtFocusGained

    private void nicTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicTxtFocusLost
       String nic=nicTxt.getText().trim();
       if(nic.isEmpty()) 
       {
           nicTxt.setForeground(Color.RED);
           nicTxt.setText("This field must be populated!!!");
        
       }
       if(nic.length()>10)
       {
            nicTxt.setForeground(Color.RED);
           nicTxt.setText("NIC number too long!!!");
           
       }
       else if(nic.length()<10)
       {
           nicTxt.setForeground(Color.RED);
           nicTxt.setText("NIC number too short!!!");
       }
       else
       {
            Pattern nicPattern = Pattern.compile("(\\d{9}[V])*");
            Matcher m = nicPattern.matcher(nic);
            if (!m.matches()) {
                nicTxt.setForeground(Color.RED);
                nicTxt.setText("Invalid NIC!!!");
            }

            
       }    
    }//GEN-LAST:event_nicTxtFocusLost

    private void nicTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicTxtFocusGained
        nicTxt.setForeground(Color.black);
        nicTxt.setText("");
    }//GEN-LAST:event_nicTxtFocusGained

    private void addTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTxtFocusGained
        addTxt.setForeground(Color.black);
        addTxt.setText(null);
    }//GEN-LAST:event_addTxtFocusGained

    private void addTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTxtFocusLost
        String ad=addTxt.getText().trim();
        if(ad.isEmpty())
        {
            addTxt.setForeground(Color.red);
            addTxt.setText("This field must be populated");
        }
    }//GEN-LAST:event_addTxtFocusLost

    private void fnameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameTxtFocusGained
        fnameTxt.setForeground(Color.black);
        fnameTxt.setText(null);
    }//GEN-LAST:event_fnameTxtFocusGained

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        String cmessage = "Do you wish to exit?";   
        String conf = "Exit Message";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf,JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
                System.exit(0);
        }
        else{
                this.dispose();
        
                DSalesMain dsm=new DSalesMain();
                dsm.setVisible(true);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addfingerprintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfingerprintBtnActionPerformed
        String ename=fnameTxt.getText().trim();
        AddFingerprint a=new AddFingerprint(ename);    
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addfingerprintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenProfileBtn;
    private javax.swing.JTextArea addTxt;
    private javax.swing.JButton addfingerprintBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton fRadBtn;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JButton homeBtn;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton mRadBtn;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JComboBox positionCmb;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
