/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;

import cwms.controller.ItemHandler;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asanka
 */
public class AddItem extends javax.swing.JFrame {
PreparedStatement prepst = null;
ResultSet res = null;
Connection dbcon = null;
    /**
     * Creates new form AddSupplier
     */
    public AddItem() {
        initComponents();
        comboFill();
        dateFill();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel38 = new javax.swing.JLabel();
        discRate1 = new javax.swing.JTextField();
        addItems = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        itemID = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        itemCat = new javax.swing.JComboBox<String>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        itemPrice = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        discRate = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        addItem = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        itemDate = new com.toedter.calendar.JDateChooser();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        itemQty = new javax.swing.JTextField();

        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Discount Rate");

        discRate1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        discRate1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discRate1.setPreferredSize(new java.awt.Dimension(6, 25));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        addItems.setBackground(new java.awt.Color(25, 77, 25));

        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Item ID");

        itemID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemID.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Item Description");

        itemName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemName.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Item Category");

        itemCat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCatActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Purchased Date");

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Unit Price (Rs.)");

        itemPrice.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        itemPrice.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Discount Rate");

        discRate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        discRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discRate.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("%");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addItem.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        addItem.setText("Add");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Add Item");

        jButton11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Exit_26px.png")); // NOI18N
        jButton11.setText("Exit");

        reset.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        itemDate.setDateFormatString("dd-MMM-yyyy");
        itemDate.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemDate.setMaxSelectableDate(new java.util.Date(4102428682000L));
        itemDate.setMinSelectableDate(new java.util.Date(946666882000L));

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Quantity");

        itemQty.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        itemQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        itemQty.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout addItemsLayout = new javax.swing.GroupLayout(addItems);
        addItems.setLayout(addItemsLayout);
        addItemsLayout.setHorizontalGroup(
            addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addItemsLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addItemsLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(itemQty, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemCat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(discRate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        addItemsLayout.setVerticalGroup(
            addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addItemsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(itemCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addItemsLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(itemQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(discRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addItemsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(addItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(addItem))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addItemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void comboFill() 
    {
        try 
        {
            dbcon = DriverManager.getConnection("jdbc:mysql://localhost/groomings_db", "root", "");
            String data = "SELECT * FROM itemcat";
            prepst = dbcon.prepareStatement(data);   
            res = prepst.executeQuery();
            itemCat.removeAllItems();

            
            while(res.next())
            {
               
                String cat = res.getString("cat");
                itemCat.addItem(cat);
                itemCat.setSelectedItem(null);

            }
                
            
        } 
        catch(SQLException e1)
        {
            e1.printStackTrace();
        }
        catch (Exception e) 
        {
            e.printStackTrace();
        } 
    }
    
    private void dateFill()
    {
        Calendar today = Calendar.getInstance();
        itemDate.setDate(today.getTime());
    }
    
    private void cleanAction()
    {       
               
        itemCat.setSelectedItem(null);
        itemID.setText(null);
        itemName.setText(null);
        itemDate.setCalendar(null);
        itemPrice.setText(null);
        itemQty.setText(null);
        discRate.setText(null);
            
            dateFill();
            
    }
    
    private void nextAction()
    {   
        itemCat.setSelectedItem(null);
        itemID.setText(null);
        itemName.setText(null);
        itemDate.setCalendar(null);
        itemPrice.setText(null);
        itemQty.setText(null);
        discRate.setText(null);
            
            dateFill();
            
            JOptionPane.showMessageDialog(null, "Item added successfully.");
        
    }
    
    private void passData()
    {
        String tmp = itemID.getText().trim();
        String iidcheck = "SELECT item_id FROM item WHERE item_id=?";
        
        try 
        {
            prepst = dbcon.prepareStatement(iidcheck);
            prepst.setString(1, tmp);
            ResultSet rest=prepst.executeQuery();
            
            if(rest.next()){
            JOptionPane.showMessageDialog(null, "The entered item ID already exist");
            }
            
            else if (itemCat.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Please select the Item Category");
            } 
                
            else if(itemID.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Item ID");
            }
            
            else if(itemName.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Item Description");
            }
        
            else if(itemDate.getDate()==null){
                JOptionPane.showMessageDialog(null, "Please select the Purchased Date");
            }
        
            else if(itemPrice.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Unit Price");
            }
            
            else if(itemQty.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Quantity");
            }
            
            else if(discRate.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter the Discount Rate");
            }
                       
            else
            {
                String id = itemID.getText().trim();
                String cat = String.valueOf(itemCat.getSelectedItem()).trim();
                String name= itemName.getText().trim();
                java.util.Date itemdate = itemDate.getDate();
                String price = itemPrice.getText().trim();
                String qty = itemQty.getText().trim();
                String rate = discRate.getText().trim();
            
                SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
                String date = df.format(itemdate);
                
                ItemHandler ih=new ItemHandler();
                ih.addItem(id,name,date,cat,price,qty,rate);
      
                   
            nextAction();
                   
            }
            
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
    }
    
    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        
        passData();
        
    }//GEN-LAST:event_addItemActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        cleanAction();
                         
    }//GEN-LAST:event_resetActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
//        Main m1=new Main();
  //      m1.setVisible(true);
    //    this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String cmessage = "Do you wish to add more items to the Database?";   
        String conf = "Exit";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf, JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_NO_OPTION){
               JOptionPane.getRootFrame().dispose();  
               cleanAction();
        }
        else
        {
            
            this.dispose();
           GRNMain m1=new GRNMain();
            m1.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void itemCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JPanel addItems;
    private javax.swing.JTextField discRate;
    private javax.swing.JTextField discRate1;
    private javax.swing.JComboBox<String> itemCat;
    private com.toedter.calendar.JDateChooser itemDate;
    private javax.swing.JTextField itemID;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemPrice;
    private javax.swing.JTextField itemQty;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
