/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;

import cwms.DataLayer.Common.ConnectionType;
import cwms.DataLayer.Common.DataBase;
import cwms.model.Employee;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class CalculateSalary extends javax.swing.JFrame {
PreparedStatement prepst = null;
ResultSet res = null;
String ename="";

    /**
     * Creates new form CalculateSalary
     */
    public CalculateSalary() {
        initComponents();
        comboLoad();
    }
    private void comboLoad()
    {
        try
        {
            DataBase db=new DataBase(ConnectionType.MYSQL);
            Connection conn=db.getConnection();
          
            String data = "SELECT `emp_name` FROM employee";
            prepst = conn.prepareStatement(data);   
            res = prepst.executeQuery();
            employeeIDCmb.removeAllItems();

            
            while(res.next())
            {
               
                ename =res.getString(1);
                //System.out.println(res.getString(1));
                employeeIDCmb.addItem(ename);
                employeeIDCmb.setSelectedItem(null);
                

            }
        }
        catch(SQLException e)
        {
            System.err.println(e);
        }
        catch(Exception e1)
        {
            System.err.println(e1);
        }
    }
    private void positionLoad()
    {
        DataBase db1=new DataBase(ConnectionType.MYSQL);
        ArrayList<Employee> em=new ArrayList<>();
        ResultSet resultset=null;
        ename=employeeIDCmb.getSelectedItem().toString();
        System.out.println(ename);
        try {
            Connection conn=db1.getConnection();
            PreparedStatement pstmt = conn.prepareStatement("SELECT emp_designation FROM employee WHERE  emp_name=?");
            pstmt.setString(1,ename);
            resultset=pstmt.executeQuery();
            
            while(resultset.next())
            {
                Employee e=new Employee(resultset.getString(1));
                em.add(e);
                
            }
            resultset.close();
            conn.close();
        }
        
        catch (SQLException ex) {
            System.out.println(ex);
        }
        catch(Exception e1) {
            System.out.println(e1);
        }
        for(Employee emp: em)
        {
            positionLbl.setText(emp.getPosition());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeIDCmb = new javax.swing.JComboBox();
        positionLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calcSalaryBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loanTxt = new javax.swing.JTextField();
        damageTxt = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        advPayTxt = new javax.swing.JTextField();

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Exit_26px.png")); // NOI18N
        jButton11.setText("Exit");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 77, 25));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculate Salary");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Name:");

        employeeIDCmb.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        employeeIDCmb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeIDCmbFocusLost(evt);
            }
        });

        positionLbl.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        positionLbl.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Position:");

        calcSalaryBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        calcSalaryBtn.setText("Calculate Salary");
        calcSalaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcSalaryBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Exit_26px.png")); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loan Amount:");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Damages:");

        resetBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        resetBtn.setText("Reset");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Advance Payment:");

        advPayTxt.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(calcSalaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(73, 73, 73)
                                .addComponent(employeeIDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(damageTxt)
                                    .addComponent(loanTxt)
                                    .addComponent(positionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                    .addComponent(advPayTxt))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(employeeIDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(positionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(loanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(damageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(advPayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcSalaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(exitBtn)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String cmessage = "Do you wish to go back to Home?";
        String conf = "Exit";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf, JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_NO_OPTION){
            JOptionPane.getRootFrame().dispose();
            //cleanAction();
        }
        else
        {

            this.dispose();
            EmployeeMain m1=new EmployeeMain();
            m1.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
             Main m1=new Main();
             m1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String cmessage = "Do you wish to go back?";
        String conf = "Exit";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf, JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            this.dispose();
            EmployeeMain em=new EmployeeMain();
            em.setVisible(true);
        }
       
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
             Main m1=new Main();
              m1.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void employeeIDCmbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeIDCmbFocusLost
        positionLoad();
    }//GEN-LAST:event_employeeIDCmbFocusLost

    private void calcSalaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcSalaryBtnActionPerformed
        double damage=0.0;
        double loanamt=0.0;
        double advp=0.0;
        String dm,lo,adp;
        dm=damageTxt.getText().trim();
        lo=loanTxt.getText().trim();
        adp=advPayTxt.getText().trim();
        //if all 3 fields are empty
        if((dm.isEmpty())&&(lo.isEmpty())&&(adp.isEmpty()))
        {
            advp=0.0;
            damage=0.0; 
            loanamt=0.0;
            
             PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
             ps.setVisible(true);
             this.dispose();
        }  
        //if lo and adp are empty
        else if((lo.isEmpty())&&(adp.isEmpty())&&(!dm.isEmpty()))
        {
            loanamt=0.0;
            advp=0.0;
            damage=Double.parseDouble(dm);
            PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
            ps.setVisible(true);
            this.dispose();
        }
         //if loan and dmg fields are empty
        else if((dm.isEmpty())&&(lo.isEmpty())&&(!adp.isEmpty()))
        {
             damage=0.0;
             loanamt=0.0;//loanamt=Double.parseDouble(lo);
             advp=Double.parseDouble(adp);
             PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
             ps.setVisible(true);
             this.dispose();
        }
        
        // if loan is empty
        if((!adp.isEmpty())&&(!dm.isEmpty())&&(lo.isEmpty()))
        {
            damage=Double.parseDouble(dm);
            advp=Double.parseDouble(adp);
            loanamt=0.0;
            PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
            ps.setVisible(true);
            this.dispose();
        }
        //if loan is not empty
        
        if((adp.isEmpty())&&(dm.isEmpty())&&(!lo.isEmpty()))
        {
            loanamt=Double.parseDouble(lo);
            advp=0.0;
            damage=0.0;
            PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
            ps.setVisible(true);
            this.dispose();
        }
        //if loan and dm are not empty
        if((adp.isEmpty())&&(!dm.isEmpty())&&(!lo.isEmpty()))
        {
            loanamt=Double.parseDouble(lo);
            advp=0.0;
            damage=Double.parseDouble(dm);
            PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
            ps.setVisible(true);
            this.dispose();
        }
        //loan and ad are not empty
        if((!adp.isEmpty())&&(dm.isEmpty())&&(!lo.isEmpty()))
        {
            loanamt=Double.parseDouble(lo);
            damage=0.0;
            advp=Double.parseDouble(adp);
            PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
            ps.setVisible(true);
            this.dispose();
        }
        //if all are full
        if((!dm.isEmpty())&&(!lo.isEmpty())&&(!adp.isEmpty()))
        {
            
             damage=Double.parseDouble(dm);
             loanamt=Double.parseDouble(lo);
             advp=Double.parseDouble(adp);
             PaySheet ps=new PaySheet(ename,positionLbl.getText().trim(),loanamt,damage,advp);
             ps.setVisible(true);
             this.dispose();
        
        }
       
    }//GEN-LAST:event_calcSalaryBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
       String cmessage = "Do you wish to exit?";   
        String conf = "Exit Message";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf,JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
                System.exit(0);
        }
        else{
                this.dispose();
        
                DSalesMain dsm=new DSalesMain();
                dsm.setVisible(true);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advPayTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton calcSalaryBtn;
    private javax.swing.JTextField damageTxt;
    private javax.swing.JComboBox employeeIDCmb;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loanTxt;
    private javax.swing.JLabel positionLbl;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
