/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;
import cwms.DataLayer.DataAccess;
import cwms.controller.EmployeeHandler;
import cwms.model.Employee;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
/**
 *
 * @author Asanka
 */
public class EmployeeProfile extends javax.swing.JFrame {
String emph="";
String emplname="";
String enic="";
String addr="";
String gend ="";
String emid="";
String empos="";
//JFrame f=new JFrame("Employee Profile");
//f.new 

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * Creates new form EmployeeProfile
     */
    public EmployeeProfile() {
        initComponents();
        resetAll();
        
         /* */     
    }

public EmployeeProfile(String eid,String ename,String enic,String eadd,String ph,String gen,String pos) {
    this();
    this.fnameTxt.setText(ename);
    this.connumTxt.setText(ph);
    this.nicTxt.setText(enic);
    this.eidLbl.setText(eid);
    this.genLbl.setText(gen);
    this.addTxt.setText(eadd);
    this.posLbl.setText(pos);
//this.JFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

}
public void resetAll() {
    eidLbl.setText("");
    fnameTxt.setText("");
    genLbl.setText("");
    addTxt.setText("");
    addTxt.setText("");
    connumTxt.setText("");
    nicTxt.setText("");
    posLbl.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        updateProBtn = new javax.swing.JButton();
        deleteProBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        fnameTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        connumTxt = new javax.swing.JTextField();
        nicTxt = new javax.swing.JTextField();
        viewattrepBtn = new javax.swing.JButton();
        eidLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        posLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 77, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 216, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 348, -1, -1));

        updateProBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        updateProBtn.setText("Update Profile");
        updateProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateProBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 479, -1, 53));

        deleteProBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        deleteProBtn.setText("Delete Profile");
        deleteProBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteProBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 479, 183, 53));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 34, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Home_26px.png")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 34, 45, 42));

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Back Arrow_26px.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 34, 45, 42));

        exitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\cwms_sherry\\project icons\\Exit_26px.png")); // NOI18N
        exitBtn.setText("Exit");
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 549, -1, -1));

        fnameTxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        fnameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameTxtFocusLost(evt);
            }
        });
        jPanel1.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 208, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Full Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NIC :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 392, -1, -1));

        connumTxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        connumTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                connumTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                connumTxtFocusLost(evt);
            }
        });
        jPanel1.add(connumTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 342, 185, -1));

        nicTxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        nicTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicTxtFocusLost(evt);
            }
        });
        jPanel1.add(nicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 386, 185, -1));

        viewattrepBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        viewattrepBtn.setText("View attendance report");
        jPanel1.add(viewattrepBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 479, 197, 53));

        eidLbl.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        eidLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(eidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 110, 185, 25));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Position:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 430, -1, -1));

        posLbl.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        posLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(posLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 430, 185, 19));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 185, 185, -1));

        genLbl.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        genLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(genLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 185, 28));

        addTxt.setColumns(20);
        addTxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        addTxt.setRows(5);
        addTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addTxtFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(addTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
         Main m1=new Main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        SearchEmployee m2=new  SearchEmployee();
        m2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProBtnActionPerformed
       String emp_id=eidLbl.getText().trim();
        int empid=Integer.parseInt(emp_id);
        String emp_name=fnameTxt.getText().trim();
        String emp_add=addTxt.getText().trim();
        String emp_con=connumTxt.getText().trim();
        String emp_nic=nicTxt.getText().trim();
        String emp_pos=posLbl.getText().trim();
        
        EmployeeHandler eh=new EmployeeHandler();
        boolean r=eh.updateEmployee(empid, emp_name, emp_nic, emp_add, emp_con);
        if(r)
        {
            JOptionPane.showMessageDialog(null,"Employee details successfully updated");
        
       
            EmployeeSummaryForm esf=new EmployeeSummaryForm(emp_id,emp_name,emp_add,genLbl.getText().trim(),emp_nic,emp_pos,emp_con);
            esf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateProBtnActionPerformed

    private void deleteProBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProBtnActionPerformed
        String empid=eidLbl.getText().trim();
        int id=Integer.parseInt(empid);
        String cmessage = "Do you wish to delete this employee?";   
        String conf = "Exit";
        int confirm = JOptionPane.showConfirmDialog(null, cmessage, conf, JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_NO_OPTION){
        EmployeeHandler eh=new EmployeeHandler();
        eh.deleteEmployee(id);
        JOptionPane.showMessageDialog(null, "Employee successfully deleted");  
        EmployeeMain em=new EmployeeMain();
        em.setVisible(true);
        this.dispose();
        
        }
        else
        {
           JOptionPane.getRootFrame().dispose();
        }
       
    }//GEN-LAST:event_deleteProBtnActionPerformed

    private void fnameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameTxtFocusGained
        fnameTxt.setForeground(Color.black);
        fnameTxt.setText(null);
    }//GEN-LAST:event_fnameTxtFocusGained

    private void fnameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameTxtFocusLost
        String fn=fnameTxt.getText().trim();
       if(fn.isEmpty()) 
       {
           fnameTxt.setForeground(Color.RED);
           fnameTxt.setText("This field must be populated");
        }
    }//GEN-LAST:event_fnameTxtFocusLost

    private void addTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTxtFocusGained
        addTxt.setForeground(Color.black);
        addTxt.setText(null);
    }//GEN-LAST:event_addTxtFocusGained

    private void addTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTxtFocusLost
       String ad=addTxt.getText().trim();
        if(ad.isEmpty())
        {
            addTxt.setForeground(Color.red);
            addTxt.setText("This field must be populated");
        }
    }//GEN-LAST:event_addTxtFocusLost

    private void connumTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_connumTxtFocusGained
        connumTxt.setForeground(Color.BLACK);
        connumTxt.setText(null);
    }//GEN-LAST:event_connumTxtFocusGained

    private void connumTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_connumTxtFocusLost
        String pn=connumTxt.getText().trim();
        
       if(pn.isEmpty()) 
       {
           connumTxt.setForeground(Color.RED);
           connumTxt.setText("This field must be populated!!!");
        
       }
       else if(pn.length()>10)
       {
           connumTxt.setForeground(Color.RED);
           connumTxt.setText("Phone number too long!!!");
           
       }
       else if(pn.length()<10)
       {
           connumTxt.setForeground(Color.RED);
           connumTxt.setText("Phone number too short!!!");
       }
      else
       {
           Pattern pnumPattern = Pattern.compile("(\\d{10})*");
           Matcher m = pnumPattern.matcher(pn);
            if (!m.matches()) {
                connumTxt.setForeground(Color.RED);
                connumTxt.setText("Invalid phone number!!!"); 
             
            }
       }
    }//GEN-LAST:event_connumTxtFocusLost

    private void nicTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicTxtFocusGained
        nicTxt.setForeground(Color.black);
        nicTxt.setText("");
    }//GEN-LAST:event_nicTxtFocusGained

    private void nicTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicTxtFocusLost
        String nic=nicTxt.getText().trim();
       if(nic.isEmpty()) 
       {
           nicTxt.setForeground(Color.RED);
           nicTxt.setText("This field must be populated!!!");
        
       }
       if(nic.length()>10)
       {
            nicTxt.setForeground(Color.RED);
           nicTxt.setText("NIC number too long!!!");
           
       }
       else if(nic.length()<10)
       {
           nicTxt.setForeground(Color.RED);
           nicTxt.setText("NIC number too short!!!");
       }
       else
       {
            Pattern nicPattern = Pattern.compile("(\\d{9}[V])*");
            Matcher m = nicPattern.matcher(nic);
            if (!m.matches()) {
                nicTxt.setForeground(Color.RED);
                nicTxt.setText("Invalid NIC!!!");
            
            }
       }    
    }//GEN-LAST:event_nicTxtFocusLost

    /**
     * @param args the command line arguments
     */
   
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField connumTxt;
    private javax.swing.JButton deleteProBtn;
    private javax.swing.JLabel eidLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel genLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nicTxt;
    private javax.swing.JLabel posLbl;
    private javax.swing.JButton updateProBtn;
    private javax.swing.JButton viewattrepBtn;
    // End of variables declaration//GEN-END:variables
}
