/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;

import cwms.DataLayer.DataAccess;
import cwms.controller.JobHandler;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asanka
 */
public class JobProfile extends javax.swing.JFrame {

    Connection con = null;
    private DefaultTableModel dtm;
    DataAccess da = new DataAccess();
    
   
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    public JobProfile() {
        initComponents();
    }
     public JobProfile(String jid, String srvid, String jname, String jprice, String time, String date, String cusid, String cusname, String vehregno, String vehcategory,String jstatus)
    {
        this();
        jobidlbl.setText(jid);
        serviceidlbl1.setText(srvid);
        jobnametxt.setText(jname);
        jobamounttxt.setText(jprice);
        timelbl.setText(time);
        datelbl.setText(date);
        cusidlbl.setText(cusid);
        cusnametxt.setText(cusname);
        vehregnotxt.setText(vehregno);
        vehcategorytxt.setText(vehcategory);
        jobstatustxt.setText(jstatus);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datelbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        timelbl = new javax.swing.JLabel();
        jobnametxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cusnametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jobamounttxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vehregnotxt = new javax.swing.JTextField();
        vehcategorytxt = new javax.swing.JTextField();
        jobidlbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        serviceidlbl1 = new javax.swing.JLabel();
        cusidlbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jobstatustxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 77, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datelbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setText("11/11/2017");
        datelbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 130, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        updatebtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        updatebtn.setText("Update Profile");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 53));

        deletebtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        deletebtn.setText("Delete Profile");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 250, 53));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job Profile");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 45, 42));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 45, 42));

        exitbtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 70, -1));

        timelbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        timelbl.setText("11.20 AM");
        jPanel1.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 80, -1));

        jobnametxt.setFont(new java.awt.Font("Microsoft JhengHei", 0, 9)); // NOI18N
        jPanel1.add(jobnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 400, 50));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Job Status :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, 30));

        cusnametxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jPanel1.add(cusnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 26));

        jobamounttxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jobamounttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobamounttxtActionPerformed(evt);
            }
        });
        jPanel1.add(jobamounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 130, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicle Category :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 26));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Job Name :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 26));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle No :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 26));

        vehregnotxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jPanel1.add(vehregnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, -1));

        vehcategorytxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jPanel1.add(vehcategorytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, -1));

        jobidlbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jobidlbl.setForeground(new java.awt.Color(255, 255, 255));
        jobidlbl.setText("J ID");
        jPanel1.add(jobidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 26));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Job ID :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 26));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer ID :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 26));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Service ID :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 26));

        serviceidlbl1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        serviceidlbl1.setForeground(new java.awt.Color(255, 255, 255));
        serviceidlbl1.setText("S ID ");
        jPanel1.add(serviceidlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 26));

        cusidlbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        cusidlbl.setForeground(new java.awt.Color(255, 255, 255));
        cusidlbl.setText("J ID");
        jPanel1.add(cusidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 26));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Amount :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jobstatustxt.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jPanel1.add(jobstatustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String jid = jobidlbl.getText();
        String jobname = jobnametxt.getText();
       
        double jobprice = Double.parseDouble(jobamounttxt.getText());
        
        String time = timelbl.getText();
        String date = datelbl.getText();   
        //String cusid = cusidtxt.getText();
        String cusname = cusnametxt.getText();
        String vehregno = vehregnotxt.getText();
        String vehcategory = vehcategorytxt.getText();
        String jstatus = jobstatustxt.getText();
       

         da.updateJob(jid,jobname,jobprice, time, date, cusname, vehregno, vehcategory,jstatus);
         JOptionPane.showMessageDialog(null, "Job successfully Updated");
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        String id = jobidlbl.getText();

        JobHandler jh = new JobHandler();
        jh.deleteJob(id);
        JOptionPane.showMessageDialog(null, "Job successfully Deleted");
         

        jobidlbl.setText("");
        jobnametxt.setText("");
        jobamounttxt.setText("");
        timelbl.setText("");
        datelbl.setText("");
        cusidlbl.setText("");
        cusnametxt.setText("");
        vehregnotxt.setText("");
        vehcategorytxt.setText("");
        
          SearchJob sj=new SearchJob();
          sj.setVisible(true);
           this.dispose();
               

    }//GEN-LAST:event_deletebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        
         SearchJob sj=new SearchJob();
         sj.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_exitbtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JobMain m1=new JobMain();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Main m1=new Main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jobamounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobamounttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobamounttxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cusidlbl;
    private javax.swing.JTextField cusnametxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jobamounttxt;
    private javax.swing.JLabel jobidlbl;
    private javax.swing.JTextField jobnametxt;
    private javax.swing.JTextField jobstatustxt;
    private javax.swing.JLabel serviceidlbl1;
    private javax.swing.JLabel timelbl;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField vehcategorytxt;
    private javax.swing.JTextField vehregnotxt;
    // End of variables declaration//GEN-END:variables
}
