/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwms.ui;

import cwms.controller.DirectSalesHandler;
import cwms.model.Directsale;
import com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets;
import cwms.DataLayer.Common.ConnectionType;
import cwms.DataLayer.Common.DataBase;
import cwms.DataLayer.DataAccess;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.AccessibleAttribute;

/**
 *
 * @author rileyghost.com rileyghost.us Rasika
 */
public class Sale extends javax.swing.JFrame {
        
    Connection con = null; //database connect
    
    private DefaultTableModel dtm;
 
    //DirectSalesHandler dsh = new DirectSalesHandler();
    DataAccess da = new DataAccess();

    public Sale() {
        initComponents();
        DataBase db=new DataBase(ConnectionType.MYSQL);
        con=db.getConnection();
        //con = DBconnect.connect(); //database connect
        currentDate();
        InvoiceId();
        dtm = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        QtyTxt = new javax.swing.JFormattedTextField();
        UpriceTxt = new javax.swing.JFormattedTextField();
        SubTotalTxt = new javax.swing.JFormattedTextField();
        addBtn = new javax.swing.JButton();
        TotalTxtF = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        paidTxt = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        balTxt = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CusNameTxt = new javax.swing.JTextField();
        ItemIdTxt = new javax.swing.JFormattedTextField();
        ItemNameTxt = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        DelBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        paidBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        payTypeComBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        invIdLable = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        oldinvlable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(25, 75, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));

        jTable1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM ID", "ITEM NAME", "QTY", "UNIT PRICE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("QTY");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UNIT PRICE");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("INVOICE ID :");

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TIME :");

        timeLable.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        timeLable.setForeground(new java.awt.Color(255, 255, 255));
        timeLable.setText("HH:MM:SS");

        dateLable.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        dateLable.setForeground(new java.awt.Color(255, 255, 255));
        dateLable.setText("DD:MM:YYYY");

        QtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyTxtActionPerformed(evt);
            }
        });
        QtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QtyTxtKeyReleased(evt);
            }
        });

        UpriceTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UpriceTxtFocusLost(evt);
            }
        });
        UpriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpriceTxtActionPerformed(evt);
            }
        });
        UpriceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpriceTxtKeyReleased(evt);
            }
        });

        addBtn.setText("INSERT DATA");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        TotalTxtF.setEditable(false);
        TotalTxtF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalTxtF.setText("0");
        TotalTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTxtFActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL");

        paidTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paidTxt.setText("0");
        paidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidTxtActionPerformed(evt);
            }
        });
        paidTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidTxtKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BALANCE");

        balTxt.setEditable(false);
        balTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balTxt.setText("0");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ITEM NAME");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CUSTOMER NAME :");

        ItemIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ItemIdTxtFocusLost(evt);
            }
        });
        ItemIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ItemIdTxtKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ITEM ID");

        DelBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        DelBtn.setText("DELETE");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        ClearBtn.setText("CLEAR");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        paidBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        paidBtn.setText("PAID");
        paidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBtnActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        payTypeComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD" }));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PAYMENT TYPE :");

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PAID");

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DATE :");

        invIdLable.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        invIdLable.setForeground(new java.awt.Color(255, 255, 255));
        invIdLable.setText("001");

        closeBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        closeBtn.setText("Exit");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        oldinvlable.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        oldinvlable.setText("oldinvid");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(payTypeComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ItemIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invIdLable, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(63, 63, 63)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel6)
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(UpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SubTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(215, 215, 215))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oldinvlable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalTxtF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paidTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(balTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(111, 111, 111)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(invIdLable, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(timeLable, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpriceTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SubTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(CusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payTypeComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TotalTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(paidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(balTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(oldinvlable, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyTxtActionPerformed

    }//GEN-LAST:event_QtyTxtActionPerformed

    private void UpriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpriceTxtActionPerformed
        try {

            double qty = Double.parseDouble(QtyTxt.getText());
            double unitprice = Double.parseDouble(UpriceTxt.getText());

            double totalprice = qty * unitprice;
            SubTotalTxt.setText("" + totalprice);

        } catch (NumberFormatException a) {

        }
    }//GEN-LAST:event_UpriceTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        String itemId = ItemIdTxt.getText();
        String itemName = ItemNameTxt.getText();

        double qty = 0;
        double unitprice = 0;

        try {
            qty = Double.parseDouble(QtyTxt.getText());
            unitprice = Double.parseDouble(UpriceTxt.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Field is Empty");
            return;
        }
        
        double total = Double.parseDouble(SubTotalTxt.getText());
      
        /***********************************************************************************/
        String itemid1 = ItemIdTxt.getText();
        String qty1 = QtyTxt.getText();
        da.removeqty(itemid1, qty1);
        /***********************************************************************************/
        
        int i;
        boolean found = false;
        
        for (i = 0; i < jTable1.getRowCount(); i++) {
            String id = jTable1.getValueAt(i, 0).toString();
            if (id.equals(itemId)) {
                found = true;
                break;
            }
        }
        
        double oldsubtotal = Double.parseDouble(TotalTxtF.getText());
        double newsubtotal = 0;

        if (found){
            
            double oldqty = Double.parseDouble(jTable1.getValueAt(i,2).toString());
            double newqty = oldqty + qty;
            double newtotal = newqty * unitprice;
            double oldtotal = Double.parseDouble(jTable1.getValueAt(i,4).toString());

            oldsubtotal -= oldtotal;
            newsubtotal = oldsubtotal + newtotal;
            
            jTable1.setValueAt(newqty,i,2);
            jTable1.setValueAt(unitprice, i,3);
            jTable1.setValueAt(newtotal,i,4);
          
        }
        else 
        {
            dtm.addRow(new Object[]{itemId, itemName, qty, unitprice, total});
                newsubtotal = oldsubtotal + total;
        }
        
        TotalTxtF.setText(""+newsubtotal);
        ItemIdTxt.setText("");
        ItemNameTxt.setText("");
        QtyTxt.setText("");
        UpriceTxt.setText("");
        SubTotalTxt.setText("");
       
    }//GEN-LAST:event_addBtnActionPerformed

    private void TotalTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTxtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTxtFActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
       
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE");
        if(x==0)
        {
           // substract total when items delete
            int z;
             for (z = 0; z < jTable1.getSelectedRowCount(); z++) {
            double oldtotalz = Double.parseDouble(TotalTxtF.getText());
            double totalz = Double.parseDouble(jTable1.getValueAt(z,4).toString());
            double newtotz = oldtotalz - totalz;
            TotalTxtF.setText(""+newtotz);
             
         }
          // delete selected row
            try
            {  
                int selectedrow =jTable1.getSelectedRow();
                if (selectedrow>=0){
                    dtm.removeRow(selectedrow);
                }else{
                    
                }
            }
            catch (Exception e)
            {

            }     
    }//GEN-LAST:event_DelBtnActionPerformed
    }
    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
    
        ItemIdTxt.setText("");
        ItemNameTxt.setText("");
        QtyTxt.setText("");
        UpriceTxt.setText("");
        SubTotalTxt.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Main m1=new Main();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DSalesMain m1=new DSalesMain();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void UpriceTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UpriceTxtFocusLost
   
    }//GEN-LAST:event_UpriceTxtFocusLost

    private void paidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidTxtActionPerformed

    private void paidTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidTxtKeyReleased
       
        double total = 0;
        double balance = 0;
        double paid = 0;
        try {
            total = Double.parseDouble(TotalTxtF.getText());
            paid = Double.parseDouble(paidTxt.getText());
            balance = paid - total;
            balTxt.setText(""+balance);
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_paidTxtKeyReleased

    private void paidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBtnActionPerformed

      int i;

        for (i = 0; i < jTable1.getRowCount(); i++) {
            String itemid = jTable1.getValueAt(i, 0).toString();
            String itemname =jTable1.getValueAt(i,1).toString();
            String qty = jTable1.getValueAt(i,2).toString();
            double unitprice = Double.parseDouble(jTable1.getValueAt(i,3).toString());
            double total = Double.parseDouble(jTable1.getValueAt(i,4).toString());
         
            //String invId = invIdLable.getText();
           int invId = Integer.parseInt(invIdLable.getText());
          //  int invoiceid = Integer.parseInt(oldinvlable.getText());
            //int invId = invoiceid+1;
            
            
            String customerName = CusNameTxt.getText();
            String paymentType = (String) payTypeComBox.getSelectedItem();
            String date = dateLable.getText();
            double ftotal = Double.parseDouble(TotalTxtF.getText());
           
            double paidamount = Double.parseDouble(paidTxt.getText());
            double balance = Double.parseDouble(balTxt.getText());
 
            da.paidInvoice(invId, customerName, paymentType, date, itemid, itemname, qty, unitprice, total, ftotal, paidamount, balance);
            
        }
       
        ItemIdTxt.setText("");
        ItemNameTxt.setText("");
        QtyTxt.setText("");
        UpriceTxt.setText("");
        SubTotalTxt.setText("");
        TotalTxtF.setText("");
        paidTxt.setText("");
        balTxt.setText("");
        CusNameTxt.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
       // model.setRowCount(0);
       
        
    }//GEN-LAST:event_paidBtnActionPerformed

    private void ItemIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ItemIdTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemIdTxtFocusLost

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    private void ItemIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ItemIdTxtKeyReleased
        DataBase db=new DataBase(ConnectionType.MYSQL);
        Connection conn=db.getConnection();
        try {
            String qq = "select * from item where item_id=?";
            PreparedStatement pst = null;
            pst = conn.prepareStatement(qq);
            pst.setString(1, (String)ItemIdTxt.getText());
            pst.execute();
            
            ResultSet set= pst.executeQuery();
            while (set.next())
            {
                ItemNameTxt.setText(set.getString("item_name"));
                UpriceTxt.setText(set.getString("unit_price"));
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_ItemIdTxtKeyReleased

    private void UpriceTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpriceTxtKeyReleased
        
        double qty = 0;
        double unitprice = 0;
        try {

            qty = Double.parseDouble(QtyTxt.getText());
            unitprice = Double.parseDouble(UpriceTxt.getText());

            double totalprice = qty * unitprice;
            SubTotalTxt.setText("" + totalprice);

        } catch (NumberFormatException a) {

        }
    }//GEN-LAST:event_UpriceTxtKeyReleased

    private void QtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyTxtKeyReleased
        double qty = 0;
        double unitprice = 0;
        try {

            qty = Double.parseDouble(QtyTxt.getText());
            unitprice = Double.parseDouble(UpriceTxt.getText());

            double totalprice = qty * unitprice;
            SubTotalTxt.setText("" + totalprice);

        } catch (NumberFormatException a) {

        }
    }//GEN-LAST:event_QtyTxtKeyReleased

     public void currentDate()
    {
        Thread clock = new Thread ()
        {
            public void run()
            {
                for(;;)
                { 
                    Calendar cal = new GregorianCalendar();
                    int day = cal.get(Calendar.DATE);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    
                    dateLable.setText(day+"-"+(month+1)+"-"+year);
        
                    int sec = cal.get(Calendar.SECOND);
                    int min = cal.get(Calendar.MINUTE);
                    int hrs = cal.get(Calendar.HOUR);
        
                    timeLable.setText(hrs+":"+min+":"+sec);
                
                    try 
                    {
                        sleep(1000);
                    }
                     catch (Exception e)
                    {
                        
                    }
                }
            }
        };
        
        clock.start();
        {
            
        } 
    }
     
      public void InvoiceId()
    {
       // String d="select * from purchase ORDER BY inv_id desc LIMIT 1";
        
        try {
            String d="SELECT * FROM purchase WHERE inv_id = (SELECT MAX(inv_id) FROM purchase) LIMIT 1";
             // System.out.println(d);
            PreparedStatement pst = con.prepareStatement(d);
            ResultSet rs = pst.executeQuery();
            rs.next();
            oldinvlable.setText(rs.getString("inv_id"));
            int oldinvoiceid = Integer.parseInt(oldinvlable.getText());
            int newinvid1 = oldinvoiceid+1;
            invIdLable.setText(Integer.toString(newinvid1));
     //      int Integer.parseInt(invIdLable.setText(newinvid));
           
          // invIdLable.setText(rs.getString("inv_id"));
        } catch (Exception e) {
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField CusNameTxt;
    private javax.swing.JButton DelBtn;
    private javax.swing.JFormattedTextField ItemIdTxt;
    private javax.swing.JFormattedTextField ItemNameTxt;
    private javax.swing.JFormattedTextField QtyTxt;
    private javax.swing.JFormattedTextField SubTotalTxt;
    private javax.swing.JFormattedTextField TotalTxtF;
    private javax.swing.JFormattedTextField UpriceTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JFormattedTextField balTxt;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel invIdLable;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel oldinvlable;
    private javax.swing.JButton paidBtn;
    private javax.swing.JFormattedTextField paidTxt;
    private javax.swing.JComboBox<String> payTypeComBox;
    private javax.swing.JLabel timeLable;
    // End of variables declaration//GEN-END:variables
}
